// <auto-generated />
namespace CC98.Share.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Intialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intialize));
        
        string IMigrationMetadata.Id
        {
            get { return "201603120649037_Intialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
